defaults:
  - _self_
  - config: resnet18

hydra:
  run:
    dir: ${config.output_dir}/${hydra:job.name}-${now:%Y-%m-%d}/${now:%H-%M-%S}

config:
  train:
    batch_size: 128
    epochs: 100
    learning_rate: 0.001

  job_name: ${hydra:job.name}
  hydra_path: ${hydra:runtime.output_dir}

